// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = AboutSliceSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type ArtDocumentDataSlicesSlice = ArtSliceSlice;

/**
 * Content for Art documents
 */
interface ArtDocumentData {
  /**
   * Slice Zone field in *Art*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: art.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArtDocumentDataSlicesSlice> /**
   * Meta Description field in *Art*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: art.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Art*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: art.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Art*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: art.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Art document from Prismic
 *
 * - **API ID**: `art`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ArtDocumentData>, "art", Lang>;

type CommissionsDocumentDataSlicesSlice = CommissionSliceSlice;

/**
 * Content for Commissions documents
 */
interface CommissionsDocumentData {
  /**
   * Slice Zone field in *Commissions*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: commissions.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CommissionsDocumentDataSlicesSlice> /**
   * Meta Description field in *Commissions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: commissions.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Commissions*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: commissions.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Commissions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: commissions.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Commissions document from Prismic
 *
 * - **API ID**: `commissions`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CommissionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CommissionsDocumentData>,
    "commissions",
    Lang
  >;

type ContactDocumentDataSlicesSlice = ContactSliceSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type CoversDocumentDataSlicesSlice = CoverSliceSlice;

/**
 * Content for Covers documents
 */
interface CoversDocumentData {
  /**
   * Slice Zone field in *Covers*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: covers.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoversDocumentDataSlicesSlice> /**
   * Meta Description field in *Covers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: covers.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Covers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: covers.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Covers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: covers.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Covers document from Prismic
 *
 * - **API ID**: `covers`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoversDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CoversDocumentData>,
    "covers",
    Lang
  >;

/**
 * Content for FeaturedArt documents
 */
interface FeaturedartDocumentData {
  /**
   * Title field in *FeaturedArt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Amount field in *FeaturedArt*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.amount
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  amount: prismic.NumberField;

  /**
   * Medium field in *FeaturedArt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.medium
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  medium: prismic.KeyTextField;

  /**
   * Image field in *FeaturedArt*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *FeaturedArt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Size field in *FeaturedArt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  size: prismic.KeyTextField;

  /**
   * Art Type field in *FeaturedArt*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: featuredart.art_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  art_type: prismic.SelectField<"Traditional Art" | "Digital Prints">;
}

/**
 * FeaturedArt document from Prismic
 *
 * - **API ID**: `featuredart`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FeaturedartDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FeaturedartDocumentData>,
    "featuredart",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = HomeSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PotraitsDocumentDataSlicesSlice = PotraitSliceSlice;

/**
 * Content for Potraits documents
 */
interface PotraitsDocumentData {
  /**
   * Slice Zone field in *Potraits*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: potraits.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PotraitsDocumentDataSlicesSlice> /**
   * Meta Description field in *Potraits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: potraits.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Potraits*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: potraits.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Potraits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: potraits.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Potraits document from Prismic
 *
 * - **API ID**: `potraits`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PotraitsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PotraitsDocumentData>,
    "potraits",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type ShopDocumentDataSlicesSlice = ShopSliceSlice;

/**
 * Content for Shop documents
 */
interface ShopDocumentData {
  /**
   * Slice Zone field in *Shop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ShopDocumentDataSlicesSlice> /**
   * Meta Description field in *Shop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: shop.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Shop*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shop.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Shop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: shop.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Shop document from Prismic
 *
 * - **API ID**: `shop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShopDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ShopDocumentData>, "shop", Lang>;

type StudiesDocumentDataSlicesSlice = StudiesSliceSlice;

/**
 * Content for Studies documents
 */
interface StudiesDocumentData {
  /**
   * Slice Zone field in *Studies*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: studies.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<StudiesDocumentDataSlicesSlice> /**
   * Meta Description field in *Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: studies.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Studies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: studies.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Studies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: studies.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Studies document from Prismic
 *
 * - **API ID**: `studies`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StudiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<StudiesDocumentData>,
    "studies",
    Lang
  >;

type WorkDocumentDataSlicesSlice = WorkSliceSlice;

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice> /**
   * Meta Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: work.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: work.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | ArtDocument
  | CommissionsDocument
  | ContactDocument
  | CoversDocument
  | FeaturedartDocument
  | HomepageDocument
  | PotraitsDocument
  | SettingsDocument
  | ShopDocument
  | StudiesDocument
  | WorkDocument;

/**
 * Primary content in *AboutSlice → Primary*
 */
export interface AboutSliceSliceDefaultPrimary {
  /**
   * Home Text field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Title field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title 2 field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_2: prismic.KeyTextField;

  /**
   * Image field in *AboutSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Description field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.image_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_description: prismic.KeyTextField;

  /**
   * Visual Text field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.visual_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  visual_text: prismic.KeyTextField;

  /**
   * Artist Text field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.artist_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist_text: prismic.KeyTextField;

  /**
   * Visual Description field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.visual_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  visual_description: prismic.KeyTextField;

  /**
   * Description field in *AboutSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Footer Image field in *AboutSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_slice.primary.footer_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSlice*
 */
type AboutSliceSliceVariation = AboutSliceSliceDefault;

/**
 * AboutSlice Shared Slice
 *
 * - **API ID**: `about_slice`
 * - **Description**: AboutSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceSlice = prismic.SharedSlice<
  "about_slice",
  AboutSliceSliceVariation
>;

/**
 * Primary content in *ArtSlice → Primary*
 */
export interface ArtSliceSliceDefaultPrimary {
  /**
   * Home Text field in *ArtSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: art_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *ArtSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: art_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Digital Text field in *ArtSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: art_slice.primary.digital_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  digital_text: prismic.KeyTextField;

  /**
   * Art Text field in *ArtSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: art_slice.primary.art_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  art_text: prismic.KeyTextField;
}

/**
 * Primary content in *ArtSlice → Items*
 */
export interface ArtSliceSliceDefaultItem {
  /**
   * Image field in *ArtSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: art_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ArtSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArtSliceSliceDefaultPrimary>,
  Simplify<ArtSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ArtSlice*
 */
type ArtSliceSliceVariation = ArtSliceSliceDefault;

/**
 * ArtSlice Shared Slice
 *
 * - **API ID**: `art_slice`
 * - **Description**: ArtSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtSliceSlice = prismic.SharedSlice<
  "art_slice",
  ArtSliceSliceVariation
>;

/**
 * Primary content in *CommissionSlice → Primary*
 */
export interface CommissionSliceSliceDefaultPrimary {
  /**
   * Home Text field in *CommissionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commission_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *CommissionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commission_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Title field in *CommissionSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: commission_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *CommissionSlice → Items*
 */
export interface CommissionSliceSliceDefaultItem {
  /**
   * Image field in *CommissionSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: commission_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CommissionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommissionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CommissionSliceSliceDefaultPrimary>,
  Simplify<CommissionSliceSliceDefaultItem>
>;

/**
 * Slice variation for *CommissionSlice*
 */
type CommissionSliceSliceVariation = CommissionSliceSliceDefault;

/**
 * CommissionSlice Shared Slice
 *
 * - **API ID**: `commission_slice`
 * - **Description**: CommissionSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommissionSliceSlice = prismic.SharedSlice<
  "commission_slice",
  CommissionSliceSliceVariation
>;

/**
 * Primary content in *ContactSlice → Primary*
 */
export interface ContactSliceSliceDefaultPrimary {
  /**
   * Home Text field in *ContactSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Nav Text field in *ContactSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.primary.shop_nav_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_nav_text: prismic.KeyTextField;

  /**
   * Title field in *ContactSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ContactSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Email field in *ContactSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Shop Text field in *ContactSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;
}

/**
 * Primary content in *ContactSlice → Items*
 */
export interface ContactSliceSliceDefaultItem {
  /**
   * Link field in *ContactSlice → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *ContactSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_slice.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for ContactSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceSliceDefaultPrimary>,
  Simplify<ContactSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ContactSlice*
 */
type ContactSliceSliceVariation = ContactSliceSliceDefault;

/**
 * ContactSlice Shared Slice
 *
 * - **API ID**: `contact_slice`
 * - **Description**: ContactSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceSlice = prismic.SharedSlice<
  "contact_slice",
  ContactSliceSliceVariation
>;

/**
 * Primary content in *CoverSlice → Primary*
 */
export interface CoverSliceSliceDefaultPrimary {
  /**
   * Home Text field in *CoverSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cover_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *CoverSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cover_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Title field in *CoverSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cover_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *CoverSlice → Items*
 */
export interface CoverSliceSliceDefaultItem {
  /**
   * Image field in *CoverSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cover_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CoverSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoverSliceSliceDefaultPrimary>,
  Simplify<CoverSliceSliceDefaultItem>
>;

/**
 * Slice variation for *CoverSlice*
 */
type CoverSliceSliceVariation = CoverSliceSliceDefault;

/**
 * CoverSlice Shared Slice
 *
 * - **API ID**: `cover_slice`
 * - **Description**: CoverSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoverSliceSlice = prismic.SharedSlice<
  "cover_slice",
  CoverSliceSliceVariation
>;

/**
 * Primary content in *Home → Primary*
 */
export interface HomeSliceDefaultPrimary {
  /**
   * Home Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Background Image field in *Home → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Image 2 field in *Home → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.background_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image_2: prismic.ImageField<never>;

  /**
   * Background Image 3 field in *Home → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.background_image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image_3: prismic.ImageField<never>;

  /**
   * Visual Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.visual_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  visual_text: prismic.KeyTextField;

  /**
   * Artist Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.artist_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist_text: prismic.KeyTextField;

  /**
   * Scroll Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.scroll_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  scroll_text: prismic.KeyTextField;

  /**
   * About Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.about_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about_text: prismic.KeyTextField;

  /**
   * About Description field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.about_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  about_description: prismic.KeyTextField;

  /**
   * Work Image field in *Home → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.work_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  work_image: prismic.ImageField<never>;

  /**
   * Work Description field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.work_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  work_description: prismic.KeyTextField;

  /**
   * To Top Text field in *Home → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.primary.to_top_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  to_top_text: prismic.KeyTextField;
}

/**
 * Default variation for Home Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Home*
 */
type HomeSliceVariation = HomeSliceDefault;

/**
 * Home Shared Slice
 *
 * - **API ID**: `home`
 * - **Description**: Home
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeSlice = prismic.SharedSlice<"home", HomeSliceVariation>;

/**
 * Primary content in *PotraitSlice → Primary*
 */
export interface PotraitSliceSliceDefaultPrimary {
  /**
   * Home Text field in *PotraitSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: potrait_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *PotraitSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: potrait_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Title field in *PotraitSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: potrait_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *PotraitSlice → Items*
 */
export interface PotraitSliceSliceDefaultItem {
  /**
   * Image field in *PotraitSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: potrait_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for PotraitSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PotraitSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PotraitSliceSliceDefaultPrimary>,
  Simplify<PotraitSliceSliceDefaultItem>
>;

/**
 * Slice variation for *PotraitSlice*
 */
type PotraitSliceSliceVariation = PotraitSliceSliceDefault;

/**
 * PotraitSlice Shared Slice
 *
 * - **API ID**: `potrait_slice`
 * - **Description**: PotraitSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PotraitSliceSlice = prismic.SharedSlice<
  "potrait_slice",
  PotraitSliceSliceVariation
>;

/**
 * Primary content in *ShopSlice → Primary*
 */
export interface ShopSliceSliceDefaultPrimary {
  /**
   * Print field in *ShopSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_slice.primary.print
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  print: prismic.KeyTextField;

  /**
   * Print 2 field in *ShopSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_slice.primary.print_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  print_2: prismic.KeyTextField;

  /**
   * Print 3 field in *ShopSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_slice.primary.print_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  print_3: prismic.KeyTextField;
}

/**
 * Primary content in *ShopSlice → Items*
 */
export interface ShopSliceSliceDefaultItem {
  /**
   * Featured field in *ShopSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: shop_slice.items[].featured
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featured: prismic.ContentRelationshipField<"featuredart">;
}

/**
 * Default variation for ShopSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShopSliceSliceDefaultPrimary>,
  Simplify<ShopSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ShopSlice*
 */
type ShopSliceSliceVariation = ShopSliceSliceDefault;

/**
 * ShopSlice Shared Slice
 *
 * - **API ID**: `shop_slice`
 * - **Description**: ShopSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopSliceSlice = prismic.SharedSlice<
  "shop_slice",
  ShopSliceSliceVariation
>;

/**
 * Primary content in *StudiesSlice → Primary*
 */
export interface StudiesSliceSliceDefaultPrimary {
  /**
   * Home Text field in *StudiesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: studies_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *StudiesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: studies_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Title field in *StudiesSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: studies_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *StudiesSlice → Items*
 */
export interface StudiesSliceSliceDefaultItem {
  /**
   * Image field in *StudiesSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: studies_slice.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for StudiesSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudiesSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudiesSliceSliceDefaultPrimary>,
  Simplify<StudiesSliceSliceDefaultItem>
>;

/**
 * Slice variation for *StudiesSlice*
 */
type StudiesSliceSliceVariation = StudiesSliceSliceDefault;

/**
 * StudiesSlice Shared Slice
 *
 * - **API ID**: `studies_slice`
 * - **Description**: StudiesSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudiesSliceSlice = prismic.SharedSlice<
  "studies_slice",
  StudiesSliceSliceVariation
>;

/**
 * Primary content in *WorkSlice → Primary*
 */
export interface WorkSliceSliceDefaultPrimary {
  /**
   * Home Text field in *WorkSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.home_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  home_text: prismic.KeyTextField;

  /**
   * Shop Text field in *WorkSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.shop_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shop_text: prismic.KeyTextField;

  /**
   * Image field in *WorkSlice → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *WorkSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Type field in *WorkSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * Description field in *WorkSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Mission field in *WorkSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.primary.mission
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mission: prismic.KeyTextField;
}

/**
 * Primary content in *WorkSlice → Items*
 */
export interface WorkSliceSliceDefaultItem {
  /**
   * Art field in *WorkSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.items[].art
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  art: prismic.KeyTextField;

  /**
   * Art Type field in *WorkSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.items[].art_type
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  art_type: prismic.KeyTextField;

  /**
   * Art Description field in *WorkSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.items[].art_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  art_description: prismic.KeyTextField;

  /**
   * Art Image field in *WorkSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_slice.items[].art_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  art_image: prismic.ImageField<never>;
}

/**
 * Default variation for WorkSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkSliceSliceDefaultPrimary>,
  Simplify<WorkSliceSliceDefaultItem>
>;

/**
 * Slice variation for *WorkSlice*
 */
type WorkSliceSliceVariation = WorkSliceSliceDefault;

/**
 * WorkSlice Shared Slice
 *
 * - **API ID**: `work_slice`
 * - **Description**: WorkSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkSliceSlice = prismic.SharedSlice<
  "work_slice",
  WorkSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      ArtDocument,
      ArtDocumentData,
      ArtDocumentDataSlicesSlice,
      CommissionsDocument,
      CommissionsDocumentData,
      CommissionsDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      CoversDocument,
      CoversDocumentData,
      CoversDocumentDataSlicesSlice,
      FeaturedartDocument,
      FeaturedartDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PotraitsDocument,
      PotraitsDocumentData,
      PotraitsDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      ShopDocument,
      ShopDocumentData,
      ShopDocumentDataSlicesSlice,
      StudiesDocument,
      StudiesDocumentData,
      StudiesDocumentDataSlicesSlice,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSliceSlice,
      AboutSliceSliceDefaultPrimary,
      AboutSliceSliceVariation,
      AboutSliceSliceDefault,
      ArtSliceSlice,
      ArtSliceSliceDefaultPrimary,
      ArtSliceSliceDefaultItem,
      ArtSliceSliceVariation,
      ArtSliceSliceDefault,
      CommissionSliceSlice,
      CommissionSliceSliceDefaultPrimary,
      CommissionSliceSliceDefaultItem,
      CommissionSliceSliceVariation,
      CommissionSliceSliceDefault,
      ContactSliceSlice,
      ContactSliceSliceDefaultPrimary,
      ContactSliceSliceDefaultItem,
      ContactSliceSliceVariation,
      ContactSliceSliceDefault,
      CoverSliceSlice,
      CoverSliceSliceDefaultPrimary,
      CoverSliceSliceDefaultItem,
      CoverSliceSliceVariation,
      CoverSliceSliceDefault,
      HomeSlice,
      HomeSliceDefaultPrimary,
      HomeSliceVariation,
      HomeSliceDefault,
      PotraitSliceSlice,
      PotraitSliceSliceDefaultPrimary,
      PotraitSliceSliceDefaultItem,
      PotraitSliceSliceVariation,
      PotraitSliceSliceDefault,
      ShopSliceSlice,
      ShopSliceSliceDefaultPrimary,
      ShopSliceSliceDefaultItem,
      ShopSliceSliceVariation,
      ShopSliceSliceDefault,
      StudiesSliceSlice,
      StudiesSliceSliceDefaultPrimary,
      StudiesSliceSliceDefaultItem,
      StudiesSliceSliceVariation,
      StudiesSliceSliceDefault,
      WorkSliceSlice,
      WorkSliceSliceDefaultPrimary,
      WorkSliceSliceDefaultItem,
      WorkSliceSliceVariation,
      WorkSliceSliceDefault,
    };
  }
}
