// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_slice: dynamic(() => import("./AboutSlice")),
  art_slice: dynamic(() => import("./ArtSlice")),
  commission_slice: dynamic(() => import("./CommissionSlice")),
  contact_slice: dynamic(() => import("./ContactSlice")),
  cover_slice: dynamic(() => import("./CoverSlice")),
  home: dynamic(() => import("./Home")),
  potrait_slice: dynamic(() => import("./PotraitSlice")),
  shop_slice: dynamic(() => import("./ShopSlice")),
  studies_slice: dynamic(() => import("./StudiesSlice")),
  work_slice: dynamic(() => import("./WorkSlice")),
};
